# Site settings & data
title: Debra Eskinazi Stockdale
author: Debra Eskinazi Stockdale
description: Personal blog and resume
url: https://myurl.com/
avatar: debra-profile.png
resume: "/static/DebraEskinaziStockdaleResume.md"
email: debra.eskinazi@gmail.com
github: Deskinazi
twitter: Debeskinazi
linkedin: debraeskinazi
stackoverflow: 1234567/username
disqus: username
google_analytics: UA-12345678-1
feed:
  subtitle: I wrote the book on electronic digital computing.
  filename: feed.xml
  path: "/feed/feed.xml"
  url: https://myurl.com/feed/feed.xml
  id: https://myurl.com/


# Build settings
markdown: kramdown
